### ISSUE TITLE
Specify Python version, generate usable requirements.txt

### ISSUE THREAD

**Issue by ericcanton** [Arcascope/pisces#4]
* Need to add description on how to create a virtual env and what version of Python is required (3.11 seems to be okay)
* module not listed in required: agcounts
* requirements don’t specify what versions of packages should be installed; as a result, the default installation doesn’t work (starting from fresh conda env)
    > as above, then run:
    > ```python
    > import matplotlib.pyplot as plt
    > from pisces.experiments import DataSetObject
    > sets = DataSetObject.find_data_sets("../data_sets")
    > walch = sets['walch_et_al']
    > hybrid = sets['hybrid_motion']
    >  # => keras issue: Could not deserialize class 'Functional' because its parent module keras.src.engine.functional cannot be imported.

**Comment by ftavella** [comment]
When trying to install `pisces` locally with:
```
cd path/to/pisces
pip install -e .
```
I got an error related to `agcounts` version:
```
ERROR: Ignored the following versions that require a different python version: 0.1.1 Requires-Python >=3.8,<3.11; 0.1.2 Requires-Python >=3.8,<3.11; 0.1.3 Requires-Python >=3.7,<3.11; 0.1.4 Requires-Python >=3.7,<3.11; 0.1.5 Requires-Python >=3.7,<3.11; 0.1.7 Requires-Python >=3.8.1,<3.12; 0.2.0 Requires-Python >=3.8.1,<3.12; 0.2.1 Requires-Python >=3.8.1,<3.12; 0.2.2 Requires-Python >=3.8.1,<3.12; 0.2.3 Requires-Python >=3.8.1,<3.12
ERROR: Could not find a version that satisfies the requirement agcounts==0.2.3 (from pisces) (from versions: none)
ERROR: No matching distribution found for agcounts==0.2.3
```
I had to manually remove it from `requirements.txt` to make it work. The same happened with `tensorflow-io-gcs-filesystem==0.36.0` and I had to remove it.

I have Python 3.12.3

I was able to install it using
```
pip install --ignore-requires-python agcounts
```

I also noticed [the CI](https://github.com/Arcascope/pisces/actions/runs/8930014408/job/24529132473#step:2:463) for #9 was failing for something similar with `etils`.

Maybe it will be better to define the requirements on `settings.ini` ([example](https://github.com/fastai/nbdev/blob/master/settings.ini))

**Comment by ericcanton** [comment]
Hm, I have tried to configure this package so that it's not compatible with Python 3.12 for this reason.

**Comment by ericcanton** [comment]
@ftavella do you know of some way to make an error if someone tries to install this package with 3.12?

**Comment by ftavella** [comment]
> @ftavella do you know of some way to make an error if someone tries to install this package with 3.12? (that is more obvious than incompatible version on some dependencies, since that encourages people to try to hack together an env)

Yes! See #10

**Comment by ftavella** [comment]
So when trying to install `pisces` with 3.11 I still get an error for ` tensorflow-io-gcs-filesystem` because it always has the `<3.11` requirement.

```
INFO: pip is looking at multiple versions of pisces to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 0.1.1 Requires-Python >=3.8,<3.11; 0.1.2 Requires-Python >=3.8,<3.11; 0.1.3 Requires-Python >=3.7,<3.11; 0.1.4 Requires-Python >=3.7,<3.11; 0.1.5 Requires-Python >=3.7,<3.11; 0.28.0 Requires-Python >=3.7, <3.11; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement tensorflow-io-gcs-filesystem==0.36.0 (from pisces) (from versions: 0.29.0, 0.30.0, 0.31.0)
ERROR: No matching distribution found for tensorflow-io-gcs-filesystem==0.36.0
```

removing this one makes the installation go smoothly. I think we can either require up to 3.10 or figure out how essential this package is, right?
